baseURL = "http://nospoonlabs.com"
theme = "LoveIt"
title = "No Spoon Labs"  # Appears hovering over the header
languageCode = "en-us"
languageName = "English"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Posts"

  [[menu.main]]
    weight = 2
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "Categories of Posts"

  [[menu.main]]
    weight = 3
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = "Tags applied to Posts"

  [[menu.main]]
    weight = 4
    identifier = "resources"
    pre = ""
    post = ""
    name = "Resources"
    url = "/resources/"
    title = "Book Reviews and Useful Links"

  [[menu.main]]
    weight = 5
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = "About the Author"

  [[menu.main]]
    weight = 6
    identifier = "rss"
    pre = ""
    post = ""
    name = "RSS"
    url = "/rss/"
    title = "Subscribe to RSS Feeds"

[params]
  # Author config
  [params.author]
    name = "Diego Scarabelli"
    email = ""
    link = ""

  # Comments config
  [params.comment]
    enable = true
    type = "giscus"
    [params.comment.giscus]
      repo = "diegoscarabelli/diegoscarabelli.github.io"
      repoId = "R_kgDOOvABDQ"
      category = "Blog Comments"
      categoryId = "DIC_kwDOOvABDc4CrUWB"
      mapping = "pathname"
      strict = "0"
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "top"
      theme = "preferred_color_scheme"
      lang = "en"
      loading = "lazy"

  # Header config
  [params.header]
    [params.header.title]
      name = "No Spoon Labs"

  # Home page config
  [params.home]
    [params.home.profile]
    subtitle = "Wake up..."

  [params.search]
    enable = true
    type = "lunr"
    placeholder = "Search..."

  [params.list]
    dateFormat = "2006-01-02"   

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"
  category = "categories"
